/* eslint-disable sonarjs/no-duplicate-string */
import { vsmProject } from "../../interfaces/VsmProject";

// The default process that we get after pressing "create new" from the front-page.
export const defaultProcess: vsmProject = {
  vsmProjectID: 448,
  name: null,
  isFavorite: false,
  duplicateOf: null,
  toBeProcessID: null,
  currentProcessId: null,
  objects: [
    {
      vsmObjectID: 3892,
      vsmProjectID: 448,
      parent: null,
      timeDefinition: null,
      time: null,
      role: null,
      childIndex: 2181,
      choiceGroup: null,
      childObjects: [
        {
          vsmObjectID: 3893,
          vsmProjectID: 448,
          parent: 3892,
          timeDefinition: null,
          time: null,
          role: null,
          childIndex: 2182,
          choiceGroup: null,
          childObjects: [],
          name: null,
          vsmObjectType: {
            pkObjectType: 2,
            name: "Supplier",
            description: null,
            hidden: true,
          },
          tasks: [],
        },
        {
          vsmObjectID: 3894,
          vsmProjectID: 448,
          parent: 3892,
          timeDefinition: null,
          time: null,
          role: null,
          childIndex: 2183,
          choiceGroup: null,
          childObjects: [],
          name: null,
          vsmObjectType: {
            pkObjectType: 3,
            name: "Input",
            description: null,
            hidden: true,
          },
          tasks: [],
        },
        {
          vsmObjectID: 3895,
          vsmProjectID: 448,
          parent: 3892,
          timeDefinition: null,
          time: null,
          role: null,
          childIndex: 2184,
          choiceGroup: null,
          childObjects: [],
          name: null,
          vsmObjectType: {
            pkObjectType: 4,
            name: "Main Activity",
            description: null,
            hidden: false,
          },
          tasks: [],
        },
        {
          vsmObjectID: 3896,
          vsmProjectID: 448,
          parent: 3892,
          timeDefinition: null,
          time: null,
          role: null,
          childIndex: 2185,
          choiceGroup: null,
          childObjects: [],
          name: null,
          vsmObjectType: {
            pkObjectType: 8,
            name: "Output",
            description: null,
            hidden: true,
          },
          tasks: [],
        },
        {
          vsmObjectID: 3897,
          vsmProjectID: 448,
          parent: 3892,
          timeDefinition: null,
          time: null,
          role: null,
          childIndex: 2186,
          choiceGroup: null,
          childObjects: [],
          name: null,
          vsmObjectType: {
            pkObjectType: 9,
            name: "Customer",
            description: null,
            hidden: true,
          },
          tasks: [],
        },
      ],
      name: null,
      vsmObjectType: {
        pkObjectType: 1,
        name: "Process",
        description: null,
        hidden: true,
      },
      tasks: [],
    },
  ],
  created: "2022-03-30T06:18:39.5356243+00:00",
  updated: "2022-03-30T06:18:39.6710778+00:00",
  updatedBy: "HSJO",
  userAccesses: [
    {
      accessId: 633,
      user: "HSJO",
      role: "Owner",
    },
  ],
  labels: [],
};

// The process that we get after pressing "create new" from the front-page, but with a name and some text added to the cards.
export const defaultProcessWithText: vsmProject = {
  vsmProjectID: 451,
  name: "Default process",
  isFavorite: false,
  duplicateOf: null,
  toBeProcessID: null,
  currentProcessId: null,
  objects: [
    {
      vsmObjectID: 3913,
      vsmProjectID: 451,
      parent: null,
      timeDefinition: null,
      time: null,
      role: null,
      childIndex: 2199,
      choiceGroup: null,
      childObjects: [
        {
          vsmObjectID: 3914,
          vsmProjectID: 451,
          parent: 3913,
          timeDefinition: null,
          time: null,
          role: null,
          childIndex: 2200,
          choiceGroup: null,
          childObjects: [],
          name: "Supplier",
          vsmObjectType: {
            pkObjectType: 2,
            name: "Supplier",
            description: null,
            hidden: true,
          },
          tasks: [],
        },
        {
          vsmObjectID: 3915,
          vsmProjectID: 451,
          parent: 3913,
          timeDefinition: null,
          time: null,
          role: null,
          childIndex: 2201,
          choiceGroup: null,
          childObjects: [],
          name: "Input",
          vsmObjectType: {
            pkObjectType: 3,
            name: "Input",
            description: null,
            hidden: true,
          },
          tasks: [],
        },
        {
          vsmObjectID: 3916,
          vsmProjectID: 451,
          parent: 3913,
          timeDefinition: null,
          time: null,
          role: null,
          childIndex: 2202,
          choiceGroup: null,
          childObjects: [],
          name: "Main Activity",
          vsmObjectType: {
            pkObjectType: 4,
            name: "Main Activity",
            description: null,
            hidden: false,
          },
          tasks: [],
        },
        {
          vsmObjectID: 3917,
          vsmProjectID: 451,
          parent: 3913,
          timeDefinition: null,
          time: null,
          role: null,
          childIndex: 2203,
          choiceGroup: null,
          childObjects: [],
          name: "Output",
          vsmObjectType: {
            pkObjectType: 8,
            name: "Output",
            description: null,
            hidden: true,
          },
          tasks: [],
        },
        {
          vsmObjectID: 3918,
          vsmProjectID: 451,
          parent: 3913,
          timeDefinition: null,
          time: null,
          role: null,
          childIndex: 2204,
          choiceGroup: null,
          childObjects: [],
          name: "Customer",
          vsmObjectType: {
            pkObjectType: 9,
            name: "Customer",
            description: null,
            hidden: true,
          },
          tasks: [],
        },
      ],
      name: null,
      vsmObjectType: {
        pkObjectType: 1,
        name: "Process",
        description: null,
        hidden: true,
      },
      tasks: [],
    },
  ],
  created: "2022-03-30T08:07:54.4461904+00:00",
  updated: "2022-03-30T12:14:39.6942546+00:00",
  updatedBy: "HSJO",
  userAccesses: [
    {
      accessId: 636,
      user: "HSJO",
      role: "Owner",
    },
  ],
  labels: [],
};

// The Flyt Developers process
export const bigProcess: vsmProject = {
  vsmProjectID: 172,
  name: "Flyt DevOps Team Process ",
  isFavorite: true,
  duplicateOf: null,
  toBeProcessID: 794,
  currentProcessId: null,
  objects: [
    {
      vsmObjectID: 2251,
      vsmProjectID: 172,
      parent: 0,
      timeDefinition: null,
      time: null,
      role: null,
      childIndex: 101,
      choiceGroup: null,
      childObjects: [
        {
          vsmObjectID: 2252,
          vsmProjectID: 172,
          parent: 2251,
          timeDefinition: null,
          time: null,
          role: null,
          childIndex: 1,
          choiceGroup: null,
          childObjects: [],
          name: "- Product owners (feature requests\n- Developers",
          vsmObjectType: {
            pkObjectType: 2,
            name: "Supplier",
            description: null,
            hidden: true,
          },
          tasks: [],
        },
        {
          vsmObjectID: 2253,
          vsmProjectID: 172,
          parent: 2251,
          timeDefinition: null,
          time: null,
          role: null,
          childIndex: 2,
          choiceGroup: null,
          childObjects: [],
          name: "Feature Requests and Bugs in our GitHub project board\nhttps://github.com/orgs/equinor/projects/87/views/8",
          vsmObjectType: {
            pkObjectType: 3,
            name: "Input",
            description: null,
            hidden: true,
          },
          tasks: [
            {
              vsmTaskID: 2831,
              fkTaskType: 1,
              taskType: {
                vsmTaskTypeID: 1,
                name: "Problem",
                description: null,
              },
              name: null,
              description:
                "Lack of clarity regarding allocation of time spent on feature development vs bug fixing vs making the technical solution robust",
              solved: false,
              solvedDate: null,
              fkProject: 172,
              objects: [],
              categories: [],
              index: 12,
              displayIndex: "P12",
            },
            {
              vsmTaskID: 2832,
              fkTaskType: 1,
              taskType: {
                vsmTaskTypeID: 1,
                name: "Problem",
                description: null,
              },
              name: null,
              description:
                "Process mentioned in input is now only covering new work from feature backlog, missing bugs and technical improvements added by developers",
              solved: false,
              solvedDate: null,
              fkProject: 172,
              objects: [],
              categories: [],
              index: 13,
              displayIndex: "P13",
            },
          ],
        },
        {
          vsmObjectID: 7047,
          vsmProjectID: 172,
          parent: 2251,
          timeDefinition: null,
          time: null,
          role: null,
          childIndex: 4,
          choiceGroup: null,
          childObjects: [
            {
              vsmObjectID: 7049,
              vsmProjectID: 172,
              parent: 7047,
              timeDefinition: "Minute",
              time: 10,
              role: "Everyone together",
              childIndex: 1,
              choiceGroup: null,
              childObjects: [],
              name: "Look over the cards in our board and confirm the state with the team.\n\nhttps://github.com/orgs/equinor/projects/77\n\nUpdate the cards if there is something unclear.",
              vsmObjectType: {
                pkObjectType: 5,
                name: "Sub Activity",
                description: null,
                hidden: false,
              },
              tasks: [],
            },
            {
              vsmObjectID: 7048,
              vsmProjectID: 172,
              parent: 7047,
              timeDefinition: "Minute",
              time: 5,
              role: "Everyone together",
              childIndex: 2,
              choiceGroup: null,
              childObjects: [],
              name: "Check that everyone knows what to do.",
              vsmObjectType: {
                pkObjectType: 5,
                name: "Sub Activity",
                description: null,
                hidden: false,
              },
              tasks: [],
            },
          ],
          name: "Daily stand-up\n\n🔁 Every workday at 09:00",
          vsmObjectType: {
            pkObjectType: 4,
            name: "Main Activity",
            description: null,
            hidden: false,
          },
          tasks: [],
        },
        {
          vsmObjectID: 7045,
          vsmProjectID: 172,
          parent: 2251,
          timeDefinition: null,
          time: null,
          role: null,
          childIndex: 6,
          choiceGroup: null,
          childObjects: [
            {
              vsmObjectID: 7046,
              vsmProjectID: 172,
              parent: 7045,
              timeDefinition: null,
              time: null,
              role: "Designer",
              childIndex: 1,
              choiceGroup: null,
              childObjects: [],
              name: "Go through all cards with the label `needs-design` and add missing information.\n\nTalk with POs if necessary to prepare the story for development.",
              vsmObjectType: {
                pkObjectType: 5,
                name: "Sub Activity",
                description: null,
                hidden: false,
              },
              tasks: [],
            },
          ],
          name: "Design",
          vsmObjectType: {
            pkObjectType: 4,
            name: "Main Activity",
            description: null,
            hidden: false,
          },
          tasks: [],
        },
        {
          vsmObjectID: 8553,
          vsmProjectID: 172,
          parent: 2251,
          timeDefinition: null,
          time: null,
          role: null,
          childIndex: 7,
          choiceGroup: null,
          childObjects: [
            {
              vsmObjectID: 7050,
              vsmProjectID: 172,
              parent: 8553,
              timeDefinition: null,
              time: null,
              role: "Designer",
              childIndex: 1,
              choiceGroup: null,
              childObjects: [],
              name: 'Designer does a "handover". Explaining the new feature to the developers.\n\nWhen design is done, move the card to `waiting on developer`.',
              vsmObjectType: {
                pkObjectType: 5,
                name: "Sub Activity",
                description: null,
                hidden: false,
              },
              tasks: [
                {
                  vsmTaskID: 1295,
                  fkTaskType: 2,
                  taskType: {
                    vsmTaskTypeID: 2,
                    name: "Question",
                    description: null,
                  },
                  name: null,
                  description:
                    "When does the PO's need to be involved in design?",
                  solved: false,
                  solvedDate: null,
                  fkProject: 172,
                  objects: [],
                  categories: [],
                  index: 5,
                  displayIndex: "Q5",
                },
              ],
            },
            {
              vsmObjectID: 9944,
              vsmProjectID: 172,
              parent: 8553,
              timeDefinition: null,
              time: null,
              role: null,
              childIndex: 2,
              choiceGroup: null,
              childObjects: [],
              name: "Add missing requirements",
              vsmObjectType: {
                pkObjectType: 5,
                name: "Sub Activity",
                description: null,
                hidden: false,
              },
              tasks: [],
            },
          ],
          name: "Approval",
          vsmObjectType: {
            pkObjectType: 4,
            name: "Main Activity",
            description: null,
            hidden: false,
          },
          tasks: [
            {
              vsmTaskID: 1638,
              fkTaskType: 1,
              taskType: {
                vsmTaskTypeID: 1,
                name: "Problem",
                description: null,
              },
              name: null,
              description: "Missing sub-activities",
              solved: false,
              solvedDate: null,
              fkProject: 172,
              objects: [],
              categories: [],
              index: 6,
              displayIndex: "P6",
            },
          ],
        },
        {
          vsmObjectID: 2254,
          vsmProjectID: 172,
          parent: 2251,
          timeDefinition: null,
          time: null,
          role: null,
          childIndex: 9,
          choiceGroup: null,
          childObjects: [
            {
              vsmObjectID: 7061,
              vsmProjectID: 172,
              parent: 2254,
              timeDefinition: null,
              time: null,
              role: null,
              childIndex: 1,
              choiceGroup: null,
              childObjects: [],
              name: "Pick a task ready for development",
              vsmObjectType: {
                pkObjectType: 5,
                name: "Sub Activity",
                description: null,
                hidden: false,
              },
              tasks: [],
            },
            {
              vsmObjectID: 17835,
              vsmProjectID: 172,
              parent: 2254,
              timeDefinition: null,
              time: null,
              role: null,
              childIndex: 2,
              choiceGroup: null,
              childObjects: [],
              name: "Move task to `in-progress`.",
              vsmObjectType: {
                pkObjectType: 5,
                name: "Sub Activity",
                description: null,
                hidden: false,
              },
              tasks: [],
            },
            {
              vsmObjectID: 2309,
              vsmProjectID: 172,
              parent: 2254,
              timeDefinition: null,
              time: null,
              role: null,
              childIndex: 3,
              choiceGroup: null,
              childObjects: [
                {
                  vsmObjectID: 2310,
                  vsmProjectID: 172,
                  parent: 2309,
                  timeDefinition: null,
                  time: null,
                  role: "Front-end Developer",
                  childIndex: 1,
                  choiceGroup: "Left",
                  childObjects: [],
                  name: "Front-end | WEB\n\nCode the changes",
                  vsmObjectType: {
                    pkObjectType: 5,
                    name: "Sub Activity",
                    description: null,
                    hidden: false,
                  },
                  tasks: [],
                },
                {
                  vsmObjectID: 2311,
                  vsmProjectID: 172,
                  parent: 2309,
                  timeDefinition: null,
                  time: null,
                  role: "Back-end Developer",
                  childIndex: 2,
                  choiceGroup: "Right",
                  childObjects: [],
                  name: "Back-end | API\n\nCode the changes",
                  vsmObjectType: {
                    pkObjectType: 5,
                    name: "Sub Activity",
                    description: null,
                    hidden: false,
                  },
                  tasks: [],
                },
                {
                  vsmObjectID: 3757,
                  vsmProjectID: 172,
                  parent: 2309,
                  timeDefinition: "Minute",
                  time: 10,
                  role: "Back-end Developer",
                  childIndex: 3,
                  choiceGroup: "Right",
                  childObjects: [],
                  name: "Deploy the API to the TEST environment in Azure",
                  vsmObjectType: {
                    pkObjectType: 5,
                    name: "Sub Activity",
                    description: null,
                    hidden: false,
                  },
                  tasks: [],
                },
                {
                  vsmObjectID: 7423,
                  vsmProjectID: 172,
                  parent: 2309,
                  timeDefinition: null,
                  time: null,
                  role: "Designer",
                  childIndex: 4,
                  choiceGroup: "Right",
                  childObjects: [],
                  name: 'Design is "done".\nMove task to approval.\n\nMaturing the story until it is ready for development.',
                  vsmObjectType: {
                    pkObjectType: 5,
                    name: "Sub Activity",
                    description: null,
                    hidden: false,
                  },
                  tasks: [],
                },
                {
                  vsmObjectID: 9312,
                  vsmProjectID: 172,
                  parent: 2309,
                  timeDefinition: null,
                  time: null,
                  role: "Back-end developer",
                  childIndex: 5,
                  choiceGroup: "Right",
                  childObjects: [],
                  name: "Notify relevant people....",
                  vsmObjectType: {
                    pkObjectType: 5,
                    name: "Sub Activity",
                    description: null,
                    hidden: false,
                  },
                  tasks: [],
                },
                {
                  vsmObjectID: 6878,
                  vsmProjectID: 172,
                  parent: 2309,
                  timeDefinition: null,
                  time: null,
                  role: "Front-end Developer",
                  childIndex: 7,
                  choiceGroup: "Left",
                  childObjects: [],
                  name: "Create a Pull Request into main-branch\n\nRequest a review from a front-end-developer",
                  vsmObjectType: {
                    pkObjectType: 5,
                    name: "Sub Activity",
                    description: null,
                    hidden: false,
                  },
                  tasks: [],
                },
                {
                  vsmObjectID: 2304,
                  vsmProjectID: 172,
                  parent: 2309,
                  timeDefinition: "Minute",
                  time: 4,
                  role: "Front-end Developer",
                  childIndex: 8,
                  choiceGroup: "Left",
                  childObjects: [],
                  name: "Deploy the client to the Test environment\n\n$yarn release-test",
                  vsmObjectType: {
                    pkObjectType: 5,
                    name: "Sub Activity",
                    description: null,
                    hidden: false,
                  },
                  tasks: [],
                },
                {
                  vsmObjectID: 4583,
                  vsmProjectID: 172,
                  parent: 2309,
                  timeDefinition: null,
                  time: null,
                  role: "Front-end Developer",
                  childIndex: 9,
                  choiceGroup: "Left",
                  childObjects: [],
                  name: "Notify tester & designer by adding a comment on the task mentioning @equinor/mad-testers + @Linedueo ",
                  vsmObjectType: {
                    pkObjectType: 5,
                    name: "Sub Activity",
                    description: null,
                    hidden: false,
                  },
                  tasks: [],
                },
              ],
              name: "Is the task for Front-end or Back-end?",
              vsmObjectType: {
                pkObjectType: 10,
                name: "Choice",
                description: null,
                hidden: false,
              },
              tasks: [],
            },
            {
              vsmObjectID: 2308,
              vsmProjectID: 172,
              parent: 2254,
              timeDefinition: null,
              time: null,
              role: "Developer",
              childIndex: 4,
              choiceGroup: null,
              childObjects: [],
              name: "Move task to Test column",
              vsmObjectType: {
                pkObjectType: 5,
                name: "Sub Activity",
                description: null,
                hidden: false,
              },
              tasks: [],
            },
          ],
          name: "Development - Implement code changes",
          vsmObjectType: {
            pkObjectType: 4,
            name: "Main Activity",
            description: null,
            hidden: false,
          },
          tasks: [
            {
              vsmTaskID: 2259,
              fkTaskType: 1,
              taskType: {
                vsmTaskTypeID: 1,
                name: "Problem",
                description: null,
              },
              name: null,
              description:
                "Problem\nWhen developing, we depend on whatever API is running in one of our environments.\n- Dev, Test, QA, and Production.\n\nIt would be nice to run everything locally: Api with a local database and mocked authentication. \nThen we could run tests quickly and not have to worry about the environment, but rather have a scope of testing that is specific to the feature we are developing.",
              solved: false,
              solvedDate: null,
              fkProject: 172,
              objects: [],
              categories: [],
              index: 9,
              displayIndex: "P9",
            },
          ],
        },
        {
          vsmObjectID: 2299,
          vsmProjectID: 172,
          parent: 2251,
          timeDefinition: null,
          time: null,
          role: null,
          childIndex: 10,
          choiceGroup: null,
          childObjects: [
            {
              vsmObjectID: 2319,
              vsmProjectID: 172,
              parent: 2299,
              timeDefinition: null,
              time: null,
              role: "Tester & Designer",
              childIndex: 1,
              choiceGroup: null,
              childObjects: [],
              name: "Test the new feature or bug-fix.",
              vsmObjectType: {
                pkObjectType: 5,
                name: "Sub Activity",
                description: null,
                hidden: false,
              },
              tasks: [],
            },
            {
              vsmObjectID: 9311,
              vsmProjectID: 172,
              parent: 2299,
              timeDefinition: null,
              time: null,
              role: "Tester & Designer",
              childIndex: 2,
              choiceGroup: null,
              childObjects: [],
              name: "Add comment about your findings",
              vsmObjectType: {
                pkObjectType: 5,
                name: "Sub Activity",
                description: null,
                hidden: false,
              },
              tasks: [],
            },
            {
              vsmObjectID: 6812,
              vsmProjectID: 172,
              parent: 2299,
              timeDefinition: null,
              time: null,
              role: null,
              childIndex: 4,
              choiceGroup: null,
              childObjects: [
                {
                  vsmObjectID: 6814,
                  vsmProjectID: 172,
                  parent: 6812,
                  timeDefinition: null,
                  time: null,
                  role: "Tester",
                  childIndex: 1,
                  choiceGroup: "Right",
                  childObjects: [],
                  name: "Inform Developer of concerns and move card back to in-progress",
                  vsmObjectType: {
                    pkObjectType: 5,
                    name: "Sub Activity",
                    description: null,
                    hidden: false,
                  },
                  tasks: [],
                },
                {
                  vsmObjectID: 2322,
                  vsmProjectID: 172,
                  parent: 6812,
                  timeDefinition: null,
                  time: null,
                  role: "Developer",
                  childIndex: 4,
                  choiceGroup: "Left",
                  childObjects: [],
                  name: "Promote to QA",
                  vsmObjectType: {
                    pkObjectType: 5,
                    name: "Sub Activity",
                    description: null,
                    hidden: false,
                  },
                  tasks: [],
                },
                {
                  vsmObjectID: 6815,
                  vsmProjectID: 172,
                  parent: 6812,
                  timeDefinition: "Minute",
                  time: 5,
                  role: "Developer",
                  childIndex: 5,
                  choiceGroup: "Left",
                  childObjects: [],
                  name: "Check that it was deployed correctly",
                  vsmObjectType: {
                    pkObjectType: 5,
                    name: "Sub Activity",
                    description: null,
                    hidden: false,
                  },
                  tasks: [],
                },
                {
                  vsmObjectID: 4091,
                  vsmProjectID: 172,
                  parent: 6812,
                  timeDefinition: null,
                  time: null,
                  role: null,
                  childIndex: 6,
                  choiceGroup: "Left",
                  childObjects: [
                    {
                      vsmObjectID: 3795,
                      vsmProjectID: 172,
                      parent: 4091,
                      timeDefinition: null,
                      time: null,
                      role: "Developer",
                      childIndex: 1,
                      choiceGroup: "Right",
                      childObjects: [],
                      name: "If it is a Bug: Move task to Pending release",
                      vsmObjectType: {
                        pkObjectType: 5,
                        name: "Sub Activity",
                        description: null,
                        hidden: false,
                      },
                      tasks: [],
                    },
                    {
                      vsmObjectID: 2318,
                      vsmProjectID: 172,
                      parent: 4091,
                      timeDefinition: null,
                      time: null,
                      role: "Developer",
                      childIndex: 2,
                      choiceGroup: "Left",
                      childObjects: [],
                      name: "Feature request: Notify POs when changes are ready for UAT\n→ Comment on the PR.",
                      vsmObjectType: {
                        pkObjectType: 5,
                        name: "Sub Activity",
                        description: null,
                        hidden: false,
                      },
                      tasks: [
                        {
                          vsmTaskID: 344,
                          fkTaskType: 2,
                          taskType: {
                            vsmTaskTypeID: 2,
                            name: "Question",
                            description: null,
                          },
                          name: null,
                          description: "Who does this? ( Ad-hoc process )",
                          solved: false,
                          solvedDate: null,
                          fkProject: 172,
                          objects: [],
                          categories: [],
                          index: 1,
                          displayIndex: "Q1",
                        },
                        {
                          vsmTaskID: 345,
                          fkTaskType: 2,
                          taskType: {
                            vsmTaskTypeID: 2,
                            name: "Question",
                            description: null,
                          },
                          name: null,
                          description:
                            "Do POs want to approve the changes before going to production?",
                          solved: false,
                          solvedDate: null,
                          fkProject: 172,
                          objects: [],
                          categories: [],
                          index: 2,
                          displayIndex: "Q2",
                        },
                        {
                          vsmTaskID: 394,
                          fkTaskType: 1,
                          taskType: {
                            vsmTaskTypeID: 1,
                            name: "Problem",
                            description: null,
                          },
                          name: null,
                          description:
                            "Lacking transparency of task progress.\nThere is no way to have the task-status public in Jira.\n\nUpdate: See I1",
                          solved: false,
                          solvedDate: null,
                          fkProject: 172,
                          objects: [],
                          categories: [],
                          index: 2,
                          displayIndex: "P2",
                        },
                        {
                          vsmTaskID: 417,
                          fkTaskType: 3,
                          taskType: {
                            vsmTaskTypeID: 3,
                            name: "Idea",
                            description: null,
                          },
                          name: null,
                          description:
                            "Task status available at https://github.com/orgs/equinor/projects/87/views/8\n\nBut it is still manually synced...",
                          solved: false,
                          solvedDate: null,
                          fkProject: 172,
                          objects: [],
                          categories: [],
                          index: 1,
                          displayIndex: "I1",
                        },
                        {
                          vsmTaskID: 568,
                          fkTaskType: 1,
                          taskType: {
                            vsmTaskTypeID: 1,
                            name: "Problem",
                            description: null,
                          },
                          name: null,
                          description:
                            "When do we want to wait on approval for release to prod and when is it ok to skip UAT?",
                          solved: false,
                          solvedDate: null,
                          fkProject: 172,
                          objects: [],
                          categories: [],
                          index: 4,
                          displayIndex: "P4",
                        },
                        {
                          vsmTaskID: 570,
                          fkTaskType: 3,
                          taskType: {
                            vsmTaskTypeID: 3,
                            name: "Idea",
                            description: null,
                          },
                          name: null,
                          description: "Automate this",
                          solved: false,
                          solvedDate: null,
                          fkProject: 172,
                          objects: [],
                          categories: [],
                          index: 2,
                          displayIndex: "I2",
                        },
                      ],
                    },
                  ],
                  name: "Involve PO's?",
                  vsmObjectType: {
                    pkObjectType: 10,
                    name: "Choice",
                    description: null,
                    hidden: false,
                  },
                  tasks: [],
                },
              ],
              name: "⇽ All is good\n-\nNot good ⇾ ",
              vsmObjectType: {
                pkObjectType: 10,
                name: "Choice",
                description: null,
                hidden: false,
              },
              tasks: [],
            },
          ],
          name: "Test\nVerify the change and test for side effects",
          vsmObjectType: {
            pkObjectType: 4,
            name: "Main Activity",
            description: null,
            hidden: false,
          },
          tasks: [
            {
              vsmTaskID: 2262,
              fkTaskType: 1,
              taskType: {
                vsmTaskTypeID: 1,
                name: "Problem",
                description: null,
              },
              name: null,
              description:
                "When testing, we want to be able to run the tests in isolation.\nToday, we need to do a lot of coordination between the front-end and back-end deployments to check what is deployed where.\nEspecially when we have multiple developers working on different features at the same time.\nThe tester also needs to be aware of potential gotchas.\n\nRelates a bit to P9 with regard to isolation.",
              solved: false,
              solvedDate: null,
              fkProject: 172,
              objects: [],
              categories: [],
              index: 10,
              displayIndex: "P10",
            },
          ],
        },
        {
          vsmObjectID: 3760,
          vsmProjectID: 172,
          parent: 2251,
          timeDefinition: null,
          time: null,
          role: null,
          childIndex: 11,
          choiceGroup: null,
          childObjects: [
            {
              vsmObjectID: 6817,
              vsmProjectID: 172,
              parent: 3760,
              timeDefinition: null,
              time: null,
              role: null,
              childIndex: 1,
              choiceGroup: null,
              childObjects: [],
              name: null,
              vsmObjectType: {
                pkObjectType: 7,
                name: "Waiting",
                description: null,
                hidden: false,
              },
              tasks: [],
            },
            {
              vsmObjectID: 6818,
              vsmProjectID: 172,
              parent: 3760,
              timeDefinition: null,
              time: null,
              role: null,
              childIndex: 2,
              choiceGroup: null,
              childObjects: [
                {
                  vsmObjectID: 6819,
                  vsmProjectID: 172,
                  parent: 6818,
                  timeDefinition: null,
                  time: null,
                  role: null,
                  childIndex: 1,
                  choiceGroup: "Left",
                  childObjects: [],
                  name: "Approved",
                  vsmObjectType: {
                    pkObjectType: 5,
                    name: "Sub Activity",
                    description: null,
                    hidden: false,
                  },
                  tasks: [],
                },
                {
                  vsmObjectID: 6820,
                  vsmProjectID: 172,
                  parent: 6818,
                  timeDefinition: null,
                  time: null,
                  role: null,
                  childIndex: 2,
                  choiceGroup: "Right",
                  childObjects: [],
                  name: "Not approved",
                  vsmObjectType: {
                    pkObjectType: 5,
                    name: "Sub Activity",
                    description: null,
                    hidden: false,
                  },
                  tasks: [],
                },
                {
                  vsmObjectID: 6821,
                  vsmProjectID: 172,
                  parent: 6818,
                  timeDefinition: null,
                  time: null,
                  role: "Tester?",
                  childIndex: 3,
                  choiceGroup: "Right",
                  childObjects: [],
                  name: "Collect feedback and move back to in-progress.",
                  vsmObjectType: {
                    pkObjectType: 5,
                    name: "Sub Activity",
                    description: null,
                    hidden: false,
                  },
                  tasks: [],
                },
                {
                  vsmObjectID: 9798,
                  vsmProjectID: 172,
                  parent: 6818,
                  timeDefinition: null,
                  time: null,
                  role: "Developer",
                  childIndex: 4,
                  choiceGroup: "Left",
                  childObjects: [],
                  name: "Squash and merge into Main-branch with a good Semantic Commit Message",
                  vsmObjectType: {
                    pkObjectType: 5,
                    name: "Sub Activity",
                    description: null,
                    hidden: false,
                  },
                  tasks: [],
                },
                {
                  vsmObjectID: 9799,
                  vsmProjectID: 172,
                  parent: 6818,
                  timeDefinition: null,
                  time: null,
                  role: null,
                  childIndex: 5,
                  choiceGroup: "Left",
                  childObjects: [],
                  name: "Release main to QA-environment.\n\n(Ensuring that QA includes the combined features that are ready for release)",
                  vsmObjectType: {
                    pkObjectType: 5,
                    name: "Sub Activity",
                    description: null,
                    hidden: false,
                  },
                  tasks: [
                    {
                      vsmTaskID: 2562,
                      fkTaskType: 2,
                      taskType: {
                        vsmTaskTypeID: 2,
                        name: "Question",
                        description: null,
                      },
                      name: null,
                      description:
                        "Maybe we should take another look at this step?\nNot super clear why this is needed. \nMaybe we could remove it?",
                      solved: false,
                      solvedDate: null,
                      fkProject: 172,
                      objects: [],
                      categories: [],
                      index: 7,
                      displayIndex: "Q7",
                    },
                  ],
                },
                {
                  vsmObjectID: 6816,
                  vsmProjectID: 172,
                  parent: 6818,
                  timeDefinition: null,
                  time: null,
                  role: "PO right away or Developers in daily",
                  childIndex: 6,
                  choiceGroup: "Left",
                  childObjects: [],
                  name: "Move task to Pending release",
                  vsmObjectType: {
                    pkObjectType: 5,
                    name: "Sub Activity",
                    description: null,
                    hidden: false,
                  },
                  tasks: [
                    {
                      vsmTaskID: 1069,
                      fkTaskType: 3,
                      taskType: {
                        vsmTaskTypeID: 3,
                        name: "Idea",
                        description: null,
                      },
                      name: null,
                      description:
                        "Is this the point where we should create/assign release branches to the feature/bug?",
                      solved: false,
                      solvedDate: null,
                      fkProject: 172,
                      objects: [],
                      categories: [],
                      index: 4,
                      displayIndex: "I4",
                    },
                  ],
                },
              ],
              name: "PO approves",
              vsmObjectType: {
                pkObjectType: 10,
                name: "Choice",
                description: null,
                hidden: false,
              },
              tasks: [],
            },
            {
              vsmObjectID: 6823,
              vsmProjectID: 172,
              parent: 3760,
              timeDefinition: null,
              time: null,
              role: null,
              childIndex: 4,
              choiceGroup: null,
              childObjects: [],
              name: "Add a comment on the GitHub Issue informing the team of the result.",
              vsmObjectType: {
                pkObjectType: 5,
                name: "Sub Activity",
                description: null,
                hidden: false,
              },
              tasks: [
                {
                  vsmTaskID: 2777,
                  fkTaskType: 1,
                  taskType: {
                    vsmTaskTypeID: 1,
                    name: "Problem",
                    description: null,
                  },
                  name: null,
                  description:
                    "Misplaced step.\n\nThis step is not positioned correctly in our process.",
                  solved: false,
                  solvedDate: null,
                  fkProject: 172,
                  objects: [],
                  categories: [],
                  index: 11,
                  displayIndex: "P11",
                },
              ],
            },
          ],
          name: "UAT - User Acceptance Testing",
          vsmObjectType: {
            pkObjectType: 4,
            name: "Main Activity",
            description: null,
            hidden: false,
          },
          tasks: [],
        },
        {
          vsmObjectID: 2300,
          vsmProjectID: 172,
          parent: 2251,
          timeDefinition: null,
          time: null,
          role: null,
          childIndex: 12,
          choiceGroup: null,
          childObjects: [
            {
              vsmObjectID: 3796,
              vsmProjectID: 172,
              parent: 2300,
              timeDefinition: null,
              time: null,
              role: "",
              childIndex: 1,
              choiceGroup: null,
              childObjects: [],
              name: "Check if Backend & Frontend changes are ready.\nCoordinate release.",
              vsmObjectType: {
                pkObjectType: 5,
                name: "Sub Activity",
                description: null,
                hidden: false,
              },
              tasks: [],
            },
            {
              vsmObjectID: 6564,
              vsmProjectID: 172,
              parent: 2300,
              timeDefinition: null,
              time: null,
              role: null,
              childIndex: 2,
              choiceGroup: null,
              childObjects: [],
              name: "If downtime is needed: Notify PO and decide on a timeframe",
              vsmObjectType: {
                pkObjectType: 5,
                name: "Sub Activity",
                description: null,
                hidden: false,
              },
              tasks: [],
            },
            {
              vsmObjectID: 17845,
              vsmProjectID: 172,
              parent: 2300,
              timeDefinition: null,
              time: null,
              role: null,
              childIndex: 3,
              choiceGroup: null,
              childObjects: [],
              name: "Put up a service message to inform our users \nhttps://web-mad-service-portal-web-prod.radix.equinor.com/Flyt\n",
              vsmObjectType: {
                pkObjectType: 5,
                name: "Sub Activity",
                description: null,
                hidden: false,
              },
              tasks: [],
            },
            {
              vsmObjectID: 2321,
              vsmProjectID: 172,
              parent: 2300,
              timeDefinition: null,
              time: null,
              role: null,
              childIndex: 4,
              choiceGroup: null,
              childObjects: [],
              name: "Release main to Production",
              vsmObjectType: {
                pkObjectType: 5,
                name: "Sub Activity",
                description: null,
                hidden: false,
              },
              tasks: [],
            },
            {
              vsmObjectID: 2401,
              vsmProjectID: 172,
              parent: 2300,
              timeDefinition: null,
              time: null,
              role: null,
              childIndex: 5,
              choiceGroup: null,
              childObjects: [],
              name: "Notify PO & users as described in: https://flyt.equinor.com/projects/83",
              vsmObjectType: {
                pkObjectType: 5,
                name: "Sub Activity",
                description: null,
                hidden: false,
              },
              tasks: [
                {
                  vsmTaskID: 1016,
                  fkTaskType: 1,
                  taskType: {
                    vsmTaskTypeID: 1,
                    name: "Problem",
                    description: null,
                  },
                  name: null,
                  description:
                    "This looks to be wrong. What is the correct process?",
                  solved: false,
                  solvedDate: null,
                  fkProject: 172,
                  objects: [],
                  categories: [],
                  index: 5,
                  displayIndex: "P5",
                },
                {
                  vsmTaskID: 1017,
                  fkTaskType: 2,
                  taskType: {
                    vsmTaskTypeID: 2,
                    name: "Question",
                    description: null,
                  },
                  name: null,
                  description:
                    "Maybe it is enough to notify POs. If I remember correctly, they are responsible for notifying the users.",
                  solved: false,
                  solvedDate: null,
                  fkProject: 172,
                  objects: [],
                  categories: [],
                  index: 3,
                  displayIndex: "Q3",
                },
              ],
            },
          ],
          name: "Plan and Deploy the Release",
          vsmObjectType: {
            pkObjectType: 4,
            name: "Main Activity",
            description: null,
            hidden: false,
          },
          tasks: [
            {
              vsmTaskID: 344,
              fkTaskType: 2,
              taskType: {
                vsmTaskTypeID: 2,
                name: "Question",
                description: null,
              },
              name: null,
              description: "Who does this? ( Ad-hoc process )",
              solved: false,
              solvedDate: null,
              fkProject: 172,
              objects: [],
              categories: [],
              index: 1,
              displayIndex: "Q1",
            },
            {
              vsmTaskID: 571,
              fkTaskType: 3,
              taskType: {
                vsmTaskTypeID: 3,
                name: "Idea",
                description: null,
              },
              name: null,
              description:
                "With UAT acceptance,:  agree with POs on a release datetime",
              solved: false,
              solvedDate: null,
              fkProject: 172,
              objects: [],
              categories: [],
              index: 3,
              displayIndex: "I3",
            },
            {
              vsmTaskID: 1900,
              fkTaskType: 1,
              taskType: {
                vsmTaskTypeID: 1,
                name: "Problem",
                description: null,
              },
              name: null,
              description:
                "API release-pipeline does not always complete. The workaround is to  try again... which feels strange.",
              solved: false,
              solvedDate: null,
              fkProject: 172,
              objects: [],
              categories: [],
              index: 7,
              displayIndex: "P7",
            },
            {
              vsmTaskID: 1901,
              fkTaskType: 1,
              taskType: {
                vsmTaskTypeID: 1,
                name: "Problem",
                description: null,
              },
              name: null,
              description: "Bugs slip through our process into production.",
              solved: false,
              solvedDate: null,
              fkProject: 172,
              objects: [],
              categories: [],
              index: 8,
              displayIndex: "P8",
            },
          ],
        },
        {
          vsmObjectID: 9878,
          vsmProjectID: 172,
          parent: 2251,
          timeDefinition: null,
          time: null,
          role: null,
          childIndex: 13,
          choiceGroup: null,
          childObjects: [
            {
              vsmObjectID: 9879,
              vsmProjectID: 172,
              parent: 9878,
              timeDefinition: null,
              time: null,
              role: null,
              childIndex: 1,
              choiceGroup: null,
              childObjects: [],
              name: "Add a service-message explaining the problem for the user.\nAs well as a link to the GitHub issue\n\nhttps://web-mad-service-portal-web-prod.radix.equinor.com/Flyt",
              vsmObjectType: {
                pkObjectType: 5,
                name: "Sub Activity",
                description: null,
                hidden: false,
              },
              tasks: [],
            },
          ],
          name: "Reacting to errors in Prod",
          vsmObjectType: {
            pkObjectType: 4,
            name: "Main Activity",
            description: null,
            hidden: false,
          },
          tasks: [],
        },
        {
          vsmObjectID: 2255,
          vsmProjectID: 172,
          parent: 2251,
          timeDefinition: null,
          time: null,
          role: null,
          childIndex: 14,
          choiceGroup: null,
          childObjects: [],
          name: "New feature, bug fix or improvement deployed to flyt.equinor.com",
          vsmObjectType: {
            pkObjectType: 8,
            name: "Output",
            description: null,
            hidden: true,
          },
          tasks: [],
        },
        {
          vsmObjectID: 2256,
          vsmProjectID: 172,
          parent: 2251,
          timeDefinition: null,
          time: null,
          role: null,
          childIndex: 15,
          choiceGroup: null,
          childObjects: [],
          name: "Flyt users",
          vsmObjectType: {
            pkObjectType: 9,
            name: "Customer",
            description: null,
            hidden: true,
          },
          tasks: [],
        },
      ],
      name: "DevOps Team Process",
      vsmObjectType: {
        pkObjectType: 1,
        name: "Process",
        description: null,
        hidden: true,
      },
      tasks: [],
    },
  ],
  created: "2021-06-29T09:06:41.1513749+00:00",
  updated: "2022-03-16T10:46:41.0333333+00:00",
  updatedBy: null,
  userAccesses: [
    {
      accessId: 5,
      user: "THOKN",
      role: "Contributor",
    },
    {
      accessId: 6,
      user: "KAREAN",
      role: "Contributor",
    },
    {
      accessId: 25,
      user: "NTOR",
      role: "Contributor",
    },
    {
      accessId: 26,
      user: "LIDU",
      role: "Contributor",
    },
    {
      accessId: 95,
      user: "MAGSA",
      role: "Contributor",
    },
    {
      accessId: 127,
      user: "MBMU",
      role: "Contributor",
    },
    {
      accessId: 1115,
      user: "HSJO",
      role: "Owner",
    },
  ],
  labels: [
    {
      id: 55,
      text: "Mobile App Development Team",
    },
  ],
};

// Process that makes a "T" shape
export const tProcess: vsmProject = {
  vsmProjectID: 385,
  name: "T-process",
  isFavorite: false,
  duplicateOf: null,
  toBeProcessID: null,
  currentProcessId: null,
  objects: [
    {
      vsmObjectID: 3241,
      vsmProjectID: 385,
      parent: null,
      timeDefinition: null,
      time: null,
      role: null,
      childIndex: 2458,
      choiceGroup: null,
      childObjects: [
        {
          vsmObjectID: 3242,
          vsmProjectID: 385,
          parent: 3241,
          timeDefinition: null,
          time: null,
          role: null,
          childIndex: 2459,
          choiceGroup: null,
          childObjects: [],
          name: null,
          vsmObjectType: {
            pkObjectType: 2,
            name: "Supplier",
            description: null,
            hidden: true,
          },
          tasks: [],
        },
        {
          vsmObjectID: 3243,
          vsmProjectID: 385,
          parent: 3241,
          timeDefinition: null,
          time: null,
          role: null,
          childIndex: 2460,
          choiceGroup: null,
          childObjects: [],
          name: null,
          vsmObjectType: {
            pkObjectType: 3,
            name: "Input",
            description: null,
            hidden: true,
          },
          tasks: [],
        },
        {
          vsmObjectID: 3244,
          vsmProjectID: 385,
          parent: 3241,
          timeDefinition: null,
          time: null,
          role: null,
          childIndex: 2461,
          choiceGroup: null,
          childObjects: [
            {
              vsmObjectID: 3247,
              vsmProjectID: 385,
              parent: 3244,
              timeDefinition: null,
              time: null,
              role: null,
              childIndex: 2465,
              choiceGroup: null,
              childObjects: [],
              name: null,
              vsmObjectType: {
                pkObjectType: 5,
                name: "Sub Activity",
                description: null,
                hidden: false,
              },
              tasks: [],
            },
            {
              vsmObjectID: 3248,
              vsmProjectID: 385,
              parent: 3244,
              timeDefinition: null,
              time: null,
              role: null,
              childIndex: 2466,
              choiceGroup: null,
              childObjects: [],
              name: null,
              vsmObjectType: {
                pkObjectType: 5,
                name: "Sub Activity",
                description: null,
                hidden: false,
              },
              tasks: [],
            },
            {
              vsmObjectID: 3249,
              vsmProjectID: 385,
              parent: 3244,
              timeDefinition: null,
              time: null,
              role: null,
              childIndex: 2467,
              choiceGroup: null,
              childObjects: [],
              name: null,
              vsmObjectType: {
                pkObjectType: 5,
                name: "Sub Activity",
                description: null,
                hidden: false,
              },
              tasks: [],
            },
            {
              vsmObjectID: 3250,
              vsmProjectID: 385,
              parent: 3244,
              timeDefinition: null,
              time: null,
              role: null,
              childIndex: 2468,
              choiceGroup: null,
              childObjects: [],
              name: null,
              vsmObjectType: {
                pkObjectType: 5,
                name: "Sub Activity",
                description: null,
                hidden: false,
              },
              tasks: [],
            },
          ],
          name: 'This process has the visual form of a "T"',
          vsmObjectType: {
            pkObjectType: 4,
            name: "Main Activity",
            description: null,
            hidden: false,
          },
          tasks: [],
        },
        {
          vsmObjectID: 3245,
          vsmProjectID: 385,
          parent: 3241,
          timeDefinition: null,
          time: null,
          role: null,
          childIndex: 2462,
          choiceGroup: null,
          childObjects: [],
          name: null,
          vsmObjectType: {
            pkObjectType: 8,
            name: "Output",
            description: null,
            hidden: true,
          },
          tasks: [],
        },
        {
          vsmObjectID: 3246,
          vsmProjectID: 385,
          parent: 3241,
          timeDefinition: null,
          time: null,
          role: null,
          childIndex: 2463,
          choiceGroup: null,
          childObjects: [],
          name: null,
          vsmObjectType: {
            pkObjectType: 9,
            name: "Customer",
            description: null,
            hidden: true,
          },
          tasks: [],
        },
      ],
      name: null,
      vsmObjectType: {
        pkObjectType: 1,
        name: "Process",
        description: null,
        hidden: true,
      },
      tasks: [],
    },
  ],
  created: "2022-03-30T09:36:59.4508673+00:00",
  updated: "2022-03-30T09:38:02.5480248+00:00",
  updatedBy: "HSJO",
  userAccesses: [
    {
      accessId: 598,
      user: "HSJO",
      role: "Owner",
    },
  ],
  labels: [],
};

// Process with implementing all the card-types (vsmObjectType)
export const allCardTypesProcess: vsmProject = {
  vsmProjectID: 453,
  name: "allCardTypesProcess",
  isFavorite: false,
  duplicateOf: 451,
  toBeProcessID: null,
  currentProcessId: null,
  objects: [
    {
      vsmObjectID: 3925,
      vsmProjectID: 453,
      parent: null,
      timeDefinition: null,
      time: null,
      role: null,
      childIndex: 2211,
      choiceGroup: null,
      childObjects: [
        {
          vsmObjectID: 3926,
          vsmProjectID: 453,
          parent: 3925,
          timeDefinition: null,
          time: null,
          role: null,
          childIndex: 2212,
          choiceGroup: null,
          childObjects: [],
          name: "Supplier",
          vsmObjectType: {
            pkObjectType: 2,
            name: "Supplier",
            description: null,
            hidden: true,
          },
          tasks: [],
        },
        {
          vsmObjectID: 3927,
          vsmProjectID: 453,
          parent: 3925,
          timeDefinition: null,
          time: null,
          role: null,
          childIndex: 2213,
          choiceGroup: null,
          childObjects: [],
          name: "Input",
          vsmObjectType: {
            pkObjectType: 3,
            name: "Input",
            description: null,
            hidden: true,
          },
          tasks: [],
        },
        {
          vsmObjectID: 3928,
          vsmProjectID: 453,
          parent: 3925,
          timeDefinition: null,
          time: null,
          role: null,
          childIndex: 2214,
          choiceGroup: null,
          childObjects: [
            {
              vsmObjectID: 3931,
              vsmProjectID: 453,
              parent: 3928,
              timeDefinition: null,
              time: null,
              role: null,
              childIndex: 2218,
              choiceGroup: null,
              childObjects: [
                {
                  vsmObjectID: 3932,
                  vsmProjectID: 453,
                  parent: 3931,
                  timeDefinition: null,
                  time: null,
                  role: null,
                  childIndex: 2218,
                  choiceGroup: "Left",
                  childObjects: [],
                  name: "SubActivity Left",
                  vsmObjectType: {
                    pkObjectType: 5,
                    name: "Sub Activity",
                    description: null,
                    hidden: false,
                  },
                  tasks: [],
                },
                {
                  vsmObjectID: 3933,
                  vsmProjectID: 453,
                  parent: 3931,
                  timeDefinition: null,
                  time: null,
                  role: null,
                  childIndex: 2219,
                  choiceGroup: "Right",
                  childObjects: [],
                  name: "SubActivity Right",
                  vsmObjectType: {
                    pkObjectType: 5,
                    name: "Sub Activity",
                    description: null,
                    hidden: false,
                  },
                  tasks: [],
                },
              ],
              name: "Choice",
              vsmObjectType: {
                pkObjectType: 10,
                name: "Choice",
                description: null,
                hidden: false,
              },
              tasks: [],
            },
            {
              vsmObjectID: 3934,
              vsmProjectID: 453,
              parent: 3928,
              timeDefinition: "Year",
              time: 200,
              role: null,
              childIndex: 2219,
              choiceGroup: null,
              childObjects: [],
              name: null,
              vsmObjectType: {
                pkObjectType: 7,
                name: "Waiting",
                description: null,
                hidden: false,
              },
              tasks: [],
            },
          ],
          name: "Main Activity",
          vsmObjectType: {
            pkObjectType: 4,
            name: "Main Activity",
            description: null,
            hidden: false,
          },
          tasks: [],
        },
        {
          vsmObjectID: 3929,
          vsmProjectID: 453,
          parent: 3925,
          timeDefinition: null,
          time: null,
          role: null,
          childIndex: 2215,
          choiceGroup: null,
          childObjects: [],
          name: "Output",
          vsmObjectType: {
            pkObjectType: 8,
            name: "Output",
            description: null,
            hidden: true,
          },
          tasks: [],
        },
        {
          vsmObjectID: 3930,
          vsmProjectID: 453,
          parent: 3925,
          timeDefinition: null,
          time: null,
          role: null,
          childIndex: 2216,
          choiceGroup: null,
          childObjects: [],
          name: "Customer",
          vsmObjectType: {
            pkObjectType: 9,
            name: "Customer",
            description: null,
            hidden: true,
          },
          tasks: [],
        },
      ],
      name: "Default process (Duplicate of 451)",
      vsmObjectType: {
        pkObjectType: 1,
        name: "Process",
        description: null,
        hidden: true,
      },
      tasks: [],
    },
  ],
  created: "2022-03-30T12:45:30.6258118+00:00",
  updated: "2022-03-30T12:47:05.2994434+00:00",
  updatedBy: "HSJO",
  userAccesses: [
    {
      accessId: 638,
      user: "HSJO",
      role: "Owner",
    },
  ],
  labels: [],
};
