name: 🐛 Bug Report
description: File a bug report
title: "Brief title"
labels: ["bug"]

body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Describe the issue here... and paste/drop in any screenshots/videos too!
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Clear, step-by-step insruction to replicate the bug
      placeholder: Provide a detailed sequence of actions to reproduce the bug
    validations:
      required: true
  - type: textarea
    id: result
    attributes:
      label: Expected results
      description: What was expected to happen
      placeholder: Describe the outcome that should have occured if the bug was not present
    validations:
      required: false
  - type: textarea
    id: results
    attributes:
      label: Actual results
      description: What actually occurred
      placeholder: Detal the incorrect or unexpected outcome observed due to the bug
    validations:
      required: true
  - type: textarea
    id: Information
    attributes:
      label: Environment details
      description: Information about the system, device, browser, or application version, provide also testdata
      placeholder: Including relevant details such as operating system, devices type, app version, etc. 
    validations:
      required: false
