export const mockApi = {
  vsmProjectID: 3414,
  name: "test",
  isFavorite: false,
  duplicateOf: null,
  toBeProcessID: 3416,
  currentProcessId: null,
  objects: [
    {
      vsmObjectID: 19595,
      vsmProjectID: 3414,
      parent: null,
      timeDefinition: null,
      time: null,
      role: null,
      childIndex: 17519,
      choiceGroup: null,
      childObjects: [19596, 19597, 19598, 19606, 19630, 19599, 19600],
      name: null,
      vsmObjectType: {
        pkObjectType: 1,
        name: "Process",
        description: null,
        hidden: true,
      },
      tasks: [],
    },
    {
      vsmObjectID: 19596,
      vsmProjectID: 3414,
      parent: 19595,
      timeDefinition: null,
      time: null,
      role: null,
      childIndex: 17520,
      choiceGroup: null,
      childObjects: [],
      name: null,
      vsmObjectType: {
        pkObjectType: 2,
        name: "Supplier",
        description: null,
        hidden: true,
      },
      tasks: [],
    },
    {
      vsmObjectID: 19597,
      vsmProjectID: 3414,
      parent: 19595,
      timeDefinition: null,
      time: null,
      role: null,
      childIndex: 17521,
      choiceGroup: null,
      childObjects: [],
      name: null,
      vsmObjectType: {
        pkObjectType: 3,
        name: "Input",
        description: null,
        hidden: true,
      },
      tasks: [],
    },
    {
      vsmObjectID: 19598,
      vsmProjectID: 3414,
      parent: 19595,
      timeDefinition: null,
      time: null,
      role: null,
      childIndex: 17522,
      choiceGroup: null,
      childObjects: [19601],
      name: "# Test Main Activity dsasd\n\n",
      vsmObjectType: {
        pkObjectType: 4,
        name: "Main Activity",
        description: null,
        hidden: false,
      },
      tasks: [],
    },
    {
      vsmObjectID: 19606,
      vsmProjectID: 3414,
      parent: 19595,
      timeDefinition: null,
      time: null,
      role: null,
      childIndex: 17523,
      choiceGroup: null,
      childObjects: [19624],
      name: null,
      vsmObjectType: {
        pkObjectType: 4,
        name: "Main Activity",
        description: null,
        hidden: false,
      },
      tasks: [
        {
          vsmTaskID: 492,
          fkTaskType: 1,
          taskType: {
            vsmTaskTypeID: 1,
            name: "Problem",
            description: null,
          },
          name: null,
          description: "test problem",
          solved: false,
          solvedDate: null,
          fkProject: 3414,
          objects: [],
          categories: [],
          index: 1,
          displayIndex: "P1",
        },
        {
          vsmTaskID: 493,
          fkTaskType: 1,
          taskType: {
            vsmTaskTypeID: 1,
            name: "Problem",
            description: null,
          },
          name: null,
          description: "test problem",
          solved: false,
          solvedDate: null,
          fkProject: 3414,
          objects: [],
          categories: [],
          index: 2,
          displayIndex: "P2",
        },
      ],
    },
    {
      vsmObjectID: 19630,
      vsmProjectID: 3414,
      parent: 19595,
      timeDefinition: null,
      time: null,
      role: null,
      childIndex: 17524,
      choiceGroup: null,
      childObjects: [],
      name: "-0",
      vsmObjectType: {
        pkObjectType: 4,
        name: "Main Activity",
        description: null,
        hidden: false,
      },
      tasks: [],
    },
    {
      vsmObjectID: 19599,
      vsmProjectID: 3414,
      parent: 19595,
      timeDefinition: null,
      time: null,
      role: null,
      childIndex: 17525,
      choiceGroup: null,
      childObjects: [],
      name: null,
      vsmObjectType: {
        pkObjectType: 8,
        name: "Output",
        description: null,
        hidden: true,
      },
      tasks: [],
    },
    {
      vsmObjectID: 19600,
      vsmProjectID: 3414,
      parent: 19595,
      timeDefinition: null,
      time: null,
      role: null,
      childIndex: 17526,
      choiceGroup: null,
      childObjects: [],
      name: null,
      vsmObjectType: {
        pkObjectType: 9,
        name: "Customer",
        description: null,
        hidden: true,
      },
      tasks: [],
    },
    {
      vsmObjectID: 19601,
      vsmProjectID: 3414,
      parent: 19598,
      timeDefinition: "Minute",
      time: 1,
      role: null,
      childIndex: 17526,
      choiceGroup: null,
      childObjects: [19602],
      name: null,
      vsmObjectType: {
        pkObjectType: 7,
        name: "Waiting",
        description: null,
        hidden: false,
      },
      tasks: [
        {
          vsmTaskID: 492,
          fkTaskType: 1,
          taskType: {
            vsmTaskTypeID: 1,
            name: "Problem",
            description: null,
          },
          name: null,
          description: "test problem",
          solved: false,
          solvedDate: null,
          fkProject: 3414,
          objects: [],
          categories: [],
          index: 1,
          displayIndex: "P1",
        },
        {
          vsmTaskID: 493,
          fkTaskType: 1,
          taskType: {
            vsmTaskTypeID: 1,
            name: "Problem",
            description: null,
          },
          name: null,
          description: "test problem",
          solved: false,
          solvedDate: null,
          fkProject: 3414,
          objects: [],
          categories: [],
          index: 2,
          displayIndex: "P2",
        },
        {
          vsmTaskID: 494,
          fkTaskType: 3,
          taskType: {
            vsmTaskTypeID: 3,
            name: "Idea",
            description: null,
          },
          name: null,
          description: "test idea",
          solved: false,
          solvedDate: null,
          fkProject: 3414,
          objects: [],
          categories: [],
          index: 1,
          displayIndex: "I1",
        },
        {
          vsmTaskID: 495,
          fkTaskType: 2,
          taskType: {
            vsmTaskTypeID: 2,
            name: "Question",
            description: null,
          },
          name: null,
          description: "test question",
          solved: false,
          solvedDate: null,
          fkProject: 3414,
          objects: [],
          categories: [],
          index: 1,
          displayIndex: "Q1",
        },
        {
          vsmTaskID: 496,
          fkTaskType: 4,
          taskType: {
            vsmTaskTypeID: 4,
            name: "Risk",
            description: null,
          },
          name: null,
          description: "test risk",
          solved: false,
          solvedDate: null,
          fkProject: 3414,
          objects: [],
          categories: [],
          index: 1,
          displayIndex: "R1",
        },
      ],
    },
    {
      vsmObjectID: 19602,
      vsmProjectID: 3414,
      parent: 19598,
      timeDefinition: null,
      time: null,
      role: null,
      childIndex: 17527,
      choiceGroup: null,
      childObjects: [19605, 19621],
      name: "",
      vsmObjectType: {
        pkObjectType: 10,
        name: "Choice",
        description: null,
        hidden: false,
      },
      tasks: [],
    },
    {
      vsmObjectID: 19605,
      vsmProjectID: 3414,
      parent: 19598,
      timeDefinition: "Minute",
      time: 10,
      role: null,
      childIndex: 17529,
      choiceGroup: null,
      childObjects: [],
      name: null,
      vsmObjectType: {
        pkObjectType: 7,
        name: "Waiting",
        description: null,
        hidden: false,
      },
      tasks: [],
    },
    {
      vsmObjectID: 19621,
      vsmProjectID: 3414,
      parent: 19598,
      timeDefinition: null,
      time: null,
      role: null,
      childIndex: 17530,
      choiceGroup: null,
      childObjects: [19627],
      name: "1 test test test teeeeeeest testestestestest testestestestestestest",
      vsmObjectType: {
        pkObjectType: 10,
        name: "Choice",
        description: null,
        hidden: false,
      },
      tasks: [],
    },
    {
      vsmObjectID: 19627,
      vsmProjectID: 3414,
      parent: 19598,
      timeDefinition: null,
      time: null,
      role: null,
      childIndex: 17531,
      choiceGroup: null,
      childObjects: [19628, 19686, 19687, 19653],
      name: "6 (merge 1)",
      vsmObjectType: {
        pkObjectType: 5,
        name: "Sub Activity",
        description: null,
        hidden: false,
      },
      tasks: [],
    },
    {
      vsmObjectID: 19628,
      vsmProjectID: 3414,
      parent: 19598,
      timeDefinition: null,
      time: null,
      role: null,
      childIndex: 17532,
      choiceGroup: null,
      childObjects: [19623],
      name: null,
      vsmObjectType: {
        pkObjectType: 7,
        name: "Waiting",
        description: null,
        hidden: false,
      },
      tasks: [],
    },
    {
      vsmObjectID: 19686,
      vsmProjectID: 3414,
      parent: 19606,
      timeDefinition: null,
      time: null,
      role: "ROLE TEST testestestestestest",
      childIndex: 17531,
      choiceGroup: null,
      childObjects: [],
      name: "Aaaaaaaaaaaaa aaaaaaaa aaaaaaaaaaaaaaa aaaaaaaaaaaaa aaaaaaaa aaaaaaaaaaaaaaa aaaaaaaaaaaaa aaaaaaaa aaaaaaaaaaaaaaa aaaaaaaaaaaaa aaaaaaaa aaaaaaaaaaaaaaa",
      vsmObjectType: {
        pkObjectType: 5,
        name: "Sub Activity",
        description: null,
        hidden: false,
      },
      tasks: [],
    },
    {
      vsmObjectID: 19687,
      vsmProjectID: 3414,
      parent: 19606,
      timeDefinition: null,
      time: null,
      role: null,
      childIndex: 17532,
      choiceGroup: null,
      childObjects: [19654, 19607],
      name: "fnshaifbuisabdsads fuisb  suibbaf siuab ufisab ufsiba fuibsaiu fbsuia bfusiab fuisabu fisa",
      vsmObjectType: {
        pkObjectType: 10,
        name: "Choice",
        description: null,
        hidden: false,
      },
      tasks: [],
    },
    {
      vsmObjectID: 19653,
      vsmProjectID: 3414,
      parent: 19630,
      timeDefinition: null,
      time: null,
      role: null,
      childIndex: 17548,
      choiceGroup: null,
      childObjects: [],
      name: "-1",
      vsmObjectType: {
        pkObjectType: 5,
        name: "Sub Activity",
        description: null,
        hidden: false,
      },
      tasks: [],
    },
    {
      vsmObjectID: 19654,
      vsmProjectID: 3414,
      parent: 19630,
      timeDefinition: null,
      time: null,
      role: null,
      childIndex: 17549,
      choiceGroup: null,
      childObjects: [19603, 19622],
      name: "-2\n",
      vsmObjectType: {
        pkObjectType: 10,
        name: "Choice",
        description: null,
        hidden: false,
      },
      tasks: [],
    },
    {
      vsmObjectID: 19607,
      vsmProjectID: 3414,
      parent: 19630,
      timeDefinition: "Hour",
      time: 28417211,
      role: "Test Roleeeeeeeeeeeeeeeeeeee",
      childIndex: 17550,
      choiceGroup: null,
      childObjects: [],
      name: "Test Sub Activity Choice 2",
      vsmObjectType: {
        pkObjectType: 5,
        name: "Sub Activity",
        description: null,
        hidden: false,
      },
      tasks: [],
    },
    {
      vsmObjectID: 19603,
      vsmProjectID: 3414,
      parent: 19602,
      timeDefinition: null,
      time: null,
      role: null,
      childIndex: 17526,
      choiceGroup: "Left",
      childObjects: [],
      name: "Test Sub Activity Choice 1",
      vsmObjectType: {
        pkObjectType: 5,
        name: "Sub Activity",
        description: null,
        hidden: false,
      },
      tasks: [],
    },
    {
      vsmObjectID: 19622,
      vsmProjectID: 3414,
      parent: 19621,
      timeDefinition: null,
      time: null,
      role: null,
      childIndex: 17541,
      choiceGroup: "Left",
      childObjects: [],
      name: "2 (1)",
      vsmObjectType: {
        pkObjectType: 5,
        name: "Sub Activity",
        description: null,
        hidden: false,
      },
      tasks: [],
    },
    {
      vsmObjectID: 19623,
      vsmProjectID: 3414,
      parent: 19621,
      timeDefinition: null,
      time: null,
      role: null,
      childIndex: 17542,
      choiceGroup: "Right",
      childObjects: [],
      name: "2 (2)",
      vsmObjectType: {
        pkObjectType: 5,
        name: "Sub Activity",
        description: null,
        hidden: false,
      },
      tasks: [],
    },
    {
      vsmObjectID: 19624,
      vsmProjectID: 3414,
      parent: 19621,
      timeDefinition: null,
      time: null,
      role: null,
      childIndex: 17543,
      choiceGroup: "Right",
      childObjects: [19629, 19679],
      name: "3",
      vsmObjectType: {
        pkObjectType: 10,
        name: "Choice",
        description: null,
        hidden: false,
      },
      tasks: [],
    },
    {
      vsmObjectID: 19629,
      vsmProjectID: 3414,
      parent: 19621,
      timeDefinition: null,
      time: null,
      role: null,
      childIndex: 17544,
      choiceGroup: "Right",
      childObjects: [],
      name: "5 (merge 1)",
      vsmObjectType: {
        pkObjectType: 5,
        name: "Sub Activity",
        description: null,
        hidden: false,
      },
      tasks: [],
    },
    {
      vsmObjectID: 19679,
      vsmProjectID: 3414,
      parent: 19678,
      timeDefinition: null,
      time: null,
      role: null,
      childIndex: 17575,
      choiceGroup: "Left",
      childObjects: [19681],
      name: "-5 (1)",
      vsmObjectType: {
        pkObjectType: 5,
        name: "Sub Activity",
        description: null,
        hidden: false,
      },
      tasks: [],
    },
    {
      vsmObjectID: 19681,
      vsmProjectID: 3414,
      parent: 19678,
      timeDefinition: null,
      time: null,
      role: null,
      childIndex: 17577,
      choiceGroup: "Right",
      childObjects: [19625, 19626],
      name: "-5 (2)",
      vsmObjectType: {
        pkObjectType: 10,
        name: "Choice",
        description: null,
        hidden: false,
      },
      tasks: [],
    },
    {
      vsmObjectID: 19684,
      vsmProjectID: 3414,
      parent: 19678,
      timeDefinition: null,
      time: null,
      role: null,
      childIndex: 17578,
      choiceGroup: "Right",
      childObjects: [],
      name: "-7",
      vsmObjectType: {
        pkObjectType: 5,
        name: "Sub Activity",
        description: null,
        hidden: false,
      },
      tasks: [],
    },
    {
      vsmObjectID: 19625,
      vsmProjectID: 3414,
      parent: 19624,
      timeDefinition: null,
      time: null,
      role: null,
      childIndex: 17543,
      choiceGroup: "Left",
      childObjects: [],
      name: "4 (1)",
      vsmObjectType: {
        pkObjectType: 5,
        name: "Sub Activity",
        description: null,
        hidden: false,
      },
      tasks: [],
    },
    {
      vsmObjectID: 19626,
      vsmProjectID: 3414,
      parent: 19624,
      timeDefinition: null,
      time: null,
      role: null,
      childIndex: 17544,
      choiceGroup: "Right",
      childObjects: [19682],
      name: "4 (2)",
      vsmObjectType: {
        pkObjectType: 5,
        name: "Sub Activity",
        description: null,
        hidden: false,
      },
      tasks: [],
    },
    {
      vsmObjectID: 19682,
      vsmProjectID: 3414,
      parent: 19681,
      timeDefinition: null,
      time: null,
      role: null,
      childIndex: 17577,
      choiceGroup: "Left",
      childObjects: [19683],
      name: "-6",
      vsmObjectType: {
        pkObjectType: 5,
        name: "Sub Activity",
        description: null,
        hidden: false,
      },
      tasks: [],
    },
    {
      vsmObjectID: 19683,
      vsmProjectID: 3414,
      parent: 19681,
      timeDefinition: null,
      time: null,
      role: null,
      childIndex: 17578,
      choiceGroup: "Right",
      childObjects: [19655],
      name: "-6 (2)",
      vsmObjectType: {
        pkObjectType: 5,
        name: "Sub Activity",
        description: null,
        hidden: false,
      },
      tasks: [],
    },
    {
      vsmObjectID: 19655,
      vsmProjectID: 3414,
      parent: 19654,
      timeDefinition: null,
      time: null,
      role: null,
      childIndex: 17559,
      choiceGroup: "Left",
      childObjects: [19608],
      name: "-3(1)",
      vsmObjectType: {
        pkObjectType: 5,
        name: "Sub Activity",
        description: null,
        hidden: false,
      },
      tasks: [
        {
          vsmTaskID: 492,
          fkTaskType: 1,
          taskType: {
            vsmTaskTypeID: 1,
            name: "Problem",
            description: null,
          },
          name: null,
          description: "test problem",
          solved: false,
          solvedDate: null,
          fkProject: 3414,
          objects: [],
          categories: [],
          index: 1,
          displayIndex: "P1",
        },
        {
          vsmTaskID: 493,
          fkTaskType: 1,
          taskType: {
            vsmTaskTypeID: 1,
            name: "Problem",
            description: null,
          },
          name: null,
          description: "test problem",
          solved: false,
          solvedDate: null,
          fkProject: 3414,
          objects: [],
          categories: [],
          index: 2,
          displayIndex: "P2",
        },
        {
          vsmTaskID: 494,
          fkTaskType: 3,
          taskType: {
            vsmTaskTypeID: 3,
            name: "Idea",
            description: null,
          },
          name: null,
          description: "test idea",
          solved: false,
          solvedDate: null,
          fkProject: 3414,
          objects: [],
          categories: [],
          index: 1,
          displayIndex: "I1",
        },
        {
          vsmTaskID: 495,
          fkTaskType: 2,
          taskType: {
            vsmTaskTypeID: 2,
            name: "Question",
            description: null,
          },
          name: null,
          description: "test question",
          solved: false,
          solvedDate: null,
          fkProject: 3414,
          objects: [],
          categories: [],
          index: 1,
          displayIndex: "Q1",
        },
        {
          vsmTaskID: 496,
          fkTaskType: 4,
          taskType: {
            vsmTaskTypeID: 4,
            name: "Risk",
            description: null,
          },
          name: null,
          description: "test risk",
          solved: false,
          solvedDate: null,
          fkProject: 3414,
          objects: [],
          categories: [],
          index: 1,
          displayIndex: "R1",
        },
      ],
    },
    {
      vsmObjectID: 19608,
      vsmProjectID: 3414,
      parent: 19654,
      timeDefinition: null,
      time: null,
      role: null,
      childIndex: 17560,
      choiceGroup: "Left",
      childObjects: [19678],
      name: null,
      vsmObjectType: {
        pkObjectType: 5,
        name: "Sub Activity",
        description: null,
        hidden: false,
      },
      tasks: [],
    },
    {
      vsmObjectID: 19656,
      vsmProjectID: 3414,
      parent: 19654,
      timeDefinition: null,
      time: null,
      role: null,
      childIndex: 17562,
      choiceGroup: "Right",
      childObjects: [],
      name: "-3(2)",
      vsmObjectType: {
        pkObjectType: 5,
        name: "Sub Activity",
        description: null,
        hidden: false,
      },
      tasks: [],
    },
    {
      vsmObjectID: 19678,
      vsmProjectID: 3414,
      parent: 19654,
      timeDefinition: null,
      time: null,
      role: null,
      childIndex: 17563,
      choiceGroup: "Right",
      childObjects: [19685, 19656],
      name: "-4",
      vsmObjectType: {
        pkObjectType: 10,
        name: "Choice",
        description: null,
        hidden: false,
      },
      tasks: [],
    },
    {
      vsmObjectID: 19685,
      vsmProjectID: 3414,
      parent: 19654,
      timeDefinition: null,
      time: null,
      role: null,
      childIndex: 17564,
      choiceGroup: "Right",
      childObjects: [],
      name: "-8",
      vsmObjectType: {
        pkObjectType: 5,
        name: "Sub Activity",
        description: null,
        hidden: false,
      },
      tasks: [],
    },
  ],
  created: "2022-09-05T11:41:59.7486472+00:00",
  updated: "2022-12-08T16:18:11.5363003+00:00",
  updatedBy: "ANESV",
  userAccesses: [
    {
      user: "ANESV",
      role: "Owner",
    },
  ],
  labels: [
    {
      id: 15,
      text: "test",
    },
  ],
};
