export const mockApi = [
  {
    children: ["19596", "19597", "19598", "19606", "19630", "19599", "19600"],
    id: "19595",
    type: "Root",
    projectId: "3414",
    index: null,
    description: null,
    role: null,
    duration: null,
    unit: null,
    tasks: [],
  },
  {
    children: [],
    id: "19596",
    type: "Supplier",
    projectId: "3414",
    index: null,
    description: null,
    role: null,
    duration: null,
    unit: null,
    tasks: [],
  },
  {
    children: [],
    id: "19597",
    type: "Input",
    projectId: "3414",
    index: null,
    description: null,
    role: null,
    duration: null,
    unit: null,
    tasks: [],
  },
  {
    children: ["19601"],
    id: "19598",
    type: "MainActivity",
    projectId: "3414",
    index: null,
    description: "# Test Main Activity dsasd\n\n",
    role: null,
    duration: null,
    unit: null,
    tasks: [],
  },
  {
    children: [],
    id: "19599",
    type: "Output",
    projectId: "3414",
    index: null,
    description: null,
    role: null,
    duration: null,
    unit: null,
    tasks: [],
  },
  {
    children: [],
    id: "19600",
    type: "Customer",
    projectId: "3414",
    index: null,
    description: null,
    role: null,
    duration: null,
    unit: null,
    tasks: [],
  },
  {
    children: ["19602"],
    id: "19601",
    type: "Waiting",
    projectId: "3414",
    index: null,
    description: null,
    role: null,
    duration: 1,
    unit: "Minute",
    tasks: [
      {
        id: "497",
        type: "Problem",
        projectId: "3414",
        description: "test",
        solved: false,
        number: 0,
      },
      {
        id: "54353",
        type: "Risk",
        projectId: "3414",
        description: "test",
        solved: false,
        number: 0,
      },
      {
        id: "654336543",
        type: "Idea",
        projectId: "3414",
        description: "test",
        solved: null,
        number: 0,
      },
      {
        id: "654365433",
        type: "Problem",
        projectId: "3414",
        description: "test",
        solved: false,
        number: 0,
      },
      {
        id: "654365443",
        type: "Risk",
        projectId: "3414",
        description: "test",
        solved: false,
        number: 0,
      },
      {
        id: "654366543",
        type: "Idea",
        projectId: "3414",
        description: "test",
        solved: null,
        number: 0,
      },
      {
        id: "754375",
        type: "Problem",
        projectId: "3414",
        description: "test",
        solved: false,
        number: 0,
      },
      {
        id: "7543754",
        type: "Risk",
        projectId: "3414",
        description: "test",
        solved: false,
        number: 0,
      },
      {
        id: "75437543",
        type: "Idea",
        projectId: "3414",
        description: "test",
        solved: null,
        number: 0,
      },
      {
        id: "7543752",
        type: "Problem",
        projectId: "3414",
        description: "test",
        solved: false,
        number: 0,
      },
      {
        id: "45327",
        type: "Risk",
        projectId: "3414",
        description: "test",
        solved: false,
        number: 0,
      },
      {
        id: "986",
        type: "Idea",
        projectId: "3414",
        description: "test",
        solved: null,
        number: 8,
      },
      {
        id: "987656",
        type: "Problem",
        projectId: "3414",
        description: "test",
        solved: false,
        number: 0,
      },
      {
        id: "8645",
        type: "Risk",
        projectId: "3414",
        description: "test",
        solved: false,
        number: 0,
      },
      {
        id: "0868060",
        type: "Idea",
        projectId: "3414",
        description: "test",
        solved: null,
        number: 0,
      },
      {
        id: "0867067",
        type: "Problem",
        projectId: "3414",
        description: "test",
        solved: false,
        number: 6,
      },
      {
        id: "+978",
        type: "Risk",
        projectId: "3414",
        description: "test",
        solved: false,
        number: 0,
      },
      {
        id: "7543",
        type: "Idea",
        projectId: "3414",
        description: "test",
        solved: null,
        number: 5,
      },
    ],
  },
  {
    children: ["19603"],
    id: "19602",
    type: "Choice",
    projectId: "3414",
    index: null,
    description: "",
    role: null,
    duration: null,
    unit: null,
    tasks: [],
  },
  {
    children: ["19605"],
    id: "19603",
    type: "SubActivity",
    projectId: "3414",
    index: null,
    description: "Test Sub Activity Choice 1",
    role: null,
    duration: null,
    unit: null,
    tasks: [],
  },
  {
    children: ["19621"],
    id: "19605",
    type: "Waiting",
    projectId: "3414",
    index: null,
    description: null,
    role: null,
    duration: 10,
    unit: "Minute",
    tasks: [],
  },
  {
    children: ["19686"],
    id: "19606",
    type: "MainActivity",
    projectId: "3414",
    index: null,
    description: null,
    role: null,
    duration: null,
    unit: null,
    tasks: [
      {
        id: "492",
        type: "Problem",
        projectId: "3414",
        description: "test problem",
        solved: false,
        number: 1,
      },
      {
        id: "493",
        type: "Problem",
        projectId: "3414",
        description: "test problem",
        solved: false,
        number: 2,
      },
      {
        id: "496",
        type: "Risk",
        projectId: "3414",
        description: "test risk",
        solved: false,
        number: 1,
      },
      {
        id: "494",
        type: "Idea",
        projectId: "3414",
        description: "test idea",
        solved: null,
        number: 1,
      },
      {
        id: "495",
        type: "Question",
        projectId: "3414",
        description: "test question",
        solved: null,
        number: 0,
      },
    ],
  },
  {
    children: [],
    id: "19607",
    type: "SubActivity",
    projectId: "3414",
    index: null,
    description: "Test Sub Activity Choice 2",
    role: "Test Roleeeeeeeeeeeeeeeeeeee",
    duration: 28417211,
    unit: "Hour",
    tasks: [],
  },
  {
    children: ["19607"],
    id: "19608",
    type: "SubActivity",
    projectId: "3414",
    index: null,
    description: "test2",
    role: null,
    duration: null,
    unit: null,
    tasks: [],
  },
  {
    children: ["19622", "19623"],
    id: "19621",
    type: "Choice",
    projectId: "3414",
    index: null,
    description:
      "1 test test test teeeeeeest testestestestest testestestestestestest",
    role: null,
    duration: null,
    unit: null,
    tasks: [],
  },
  {
    children: ["19627"],
    id: "19622",
    type: "SubActivity",
    projectId: "3414",
    index: null,
    description: "2 (1)",
    role: null,
    duration: null,
    unit: null,
    tasks: [],
  },
  {
    children: ["19624"],
    id: "19623",
    type: "SubActivity",
    projectId: "3414",
    index: null,
    description: "2 (2)",
    role: null,
    duration: null,
    unit: null,
    tasks: [],
  },
  {
    children: ["19625", "19626"],
    id: "19624",
    type: "Choice",
    projectId: "3414",
    index: null,
    description: "3",
    role: null,
    duration: null,
    unit: null,
    tasks: [],
  },
  {
    children: ["19627", "19629"],
    id: "19625",
    type: "SubActivity",
    projectId: "3414",
    index: null,
    description: "4 (1)",
    role: null,
    duration: null,
    unit: null,
    tasks: [],
  },
  {
    children: ["19627", "19629"],
    id: "19626",
    type: "SubActivity",
    projectId: "3414",
    index: null,
    description: "4 (2)",
    role: null,
    duration: null,
    unit: null,
    tasks: [],
  },
  {
    children: ["19628"],
    id: "19627",
    type: "SubActivity",
    projectId: "3414",
    index: null,
    description: "6 (merge 1)",
    role: null,
    duration: null,
    unit: null,
    tasks: [],
  },
  {
    children: [],
    id: "19628",
    type: "Waiting",
    projectId: "3414",
    index: null,
    description: null,
    role: null,
    duration: null,
    unit: null,
    tasks: [],
  },
  {
    children: ["19627"],
    id: "19629",
    type: "SubActivity",
    projectId: "3414",
    index: null,
    description: "5 (merge 1)",
    role: null,
    duration: null,
    unit: null,
    tasks: [],
  },
  {
    children: ["19653"],
    id: "19630",
    type: "MainActivity",
    projectId: "3414",
    index: null,
    description: "-0",
    role: null,
    duration: null,
    unit: null,
    tasks: [],
  },
  {
    children: ["19654"],
    id: "19653",
    type: "SubActivity",
    projectId: "3414",
    index: null,
    description: "-1",
    role: null,
    duration: null,
    unit: null,
    tasks: [],
  },
  {
    children: ["19655", "19656"],
    id: "19654",
    type: "Choice",
    projectId: "3414",
    index: null,
    description: "-2\n",
    role: null,
    duration: null,
    unit: null,
    tasks: [],
  },
  {
    children: ["19608"],
    id: "19655",
    type: "SubActivity",
    projectId: "3414",
    index: null,
    description: "-3(1",
    role: null,
    duration: null,
    unit: null,
    tasks: [],
  },
  {
    children: ["19678"],
    id: "19656",
    type: "SubActivity",
    projectId: "3414",
    index: null,
    description: "-3(2)",
    role: null,
    duration: null,
    unit: null,
    tasks: [],
  },
  {
    children: ["19679", "19681"],
    id: "19678",
    type: "Choice",
    projectId: "3414",
    index: null,
    description: "-4",
    role: null,
    duration: null,
    unit: null,
    tasks: [],
  },
  {
    children: ["19685", "19607"],
    id: "19679",
    type: "SubActivity",
    projectId: "3414",
    index: null,
    description: "-5 (1)",
    role: null,
    duration: null,
    unit: null,
    tasks: [],
  },
  {
    children: ["19684"],
    id: "19681",
    type: "Choice",
    projectId: "3414",
    index: null,
    description: "-5 (2)",
    role: null,
    duration: null,
    unit: null,
    tasks: [],
  },
  {
    children: ["19607"],
    id: "19682",
    type: "SubActivity",
    projectId: "3414",
    index: null,
    description: "-6",
    role: null,
    duration: null,
    unit: null,
    tasks: [],
  },
  {
    children: ["19607"],
    id: "19683",
    type: "SubActivity",
    projectId: "3414",
    index: null,
    description: "-6 (2)",
    role: null,
    duration: null,
    unit: null,
    tasks: [],
  },
  {
    children: ["19685", "19607"],
    id: "19684",
    type: "SubActivity",
    projectId: "3414",
    index: null,
    description: "-7",
    role: null,
    duration: null,
    unit: null,
    tasks: [],
  },
  {
    children: ["19607"],
    id: "19685",
    type: "SubActivity",
    projectId: "3414",
    index: null,
    description: "-8",
    role: null,
    duration: null,
    unit: null,
    tasks: [],
  },
  {
    children: ["19687"],
    id: "19686",
    type: "SubActivity",
    projectId: "3414",
    index: null,
    description:
      "Aaaaaaaaaaaaa aaaaaaaa aaaaaaaaaaaaaaa aaaaaaaaaaaaa aaaaaaaa aaaaaaaaaaaaaaa aaaaaaaaaaaaa aaaaaaaa aaaaaaaaaaaaaaa aaaaaaaaaaaaa aaaaaaaa aaaaaaaaaaaaaaa",
    role: "ROLE TEST testestestestestest",
    duration: null,
    unit: null,
    tasks: [],
  },
  {
    children: [],
    id: "19687",
    type: "Choice",
    projectId: "3414",
    index: null,
    description:
      "fnshaifbuisabdsads fuisb  suibbaf siuab ufisab ufsiba fuibsaiu fbsuia bfusiab fuisabu fisa",
    role: null,
    duration: null,
    unit: null,
    tasks: [],
  },
];
